/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    uint32_t *pSHCSR = (uint32_t *) 0xE000ED24;

    *pSHCSR |= (1 << 16);
    *pSHCSR |= (1 << 17);
    *pSHCSR |= (1 << 18);

    uint32_t  *pSRAM = (uint32_t *) 0x20010000;

    *pSRAM = 0xFFFFFFFF;

    void (*some_address) (void);
    some_address = (void *)0x20010001;

    some_address();


	for(;;);
}

void HardFault_Handler(void)
{
	printf("In Hardfault\n");
	while(1);
}

void MemManage_Handler(void)
{
	printf("In Memmanage\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("In Busfault\n");
	while(1);
}

void UsageFault_Handler(void)
{
	__asm ("MRS R0,MSP");
	register uint32_t msp_value __asm("r0");
	uint32_t *pMSP = (uint32_t *)msp_value;

	uint32_t *pUFSR = (uint32_t *)0xE000ED2A;
	*pUFSR &= (0xFFFF);

	printf("In Usagefault\n");
	printf("UsageFault:%lx\n",*pUFSR);
	printf("MSP: %p\n",pMSP);
	while(1);
}

